version: "3.9"
services:

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network-test
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerDB
      MYSQL_USER: user1
      MYSQL_PASSWORD: 15020
    ports:
      - "3308:3306"
    networks:
      - spring-network-test
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network-test:
volumes:
  mysql-volume: